name: Feature Request
description: Suggest an idea or new feature for WizardMerge
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Backend (C++)
        - Frontend - Qt6 Desktop
        - Frontend - Next.js Web
        - Frontend - CLI
        - Merge Algorithm
        - Git Integration
        - UI/UX
        - Documentation
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: phase
    attributes:
      label: Roadmap Phase
      description: If applicable, which roadmap phase does this align with?
      options:
        - Phase 1 - Foundation
        - Phase 2 - Intelligence & Usability
        - Phase 3 - Advanced Features
        - Not in current roadmap
    validations:
      required: false
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the motivation?
      placeholder: Describe the problem or need...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe your proposed solution...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What alternatives have you considered?
  
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this feature?
      placeholder: |
        - Better user experience
        - Faster conflict resolution
        - More accurate merging
        - etc.
  
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: If you have ideas about how to implement this, share them here
      placeholder: Technical implementation details...
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
      placeholder: Any additional information...
